version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - './logs:/usr/app/logs'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    networks:
      - postgres-app-network
    restart: unless-stopped
  postgres:
    build: ./database
    volumes:
      - './database/db/:/usr/db'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: ${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres-app-network
    restart: unless-stopped
networks:
  postgres-app-network:
    driver: bridge
